# ============= 本番環境 ==================
version: '3'
services:
  app:
    build:
      context: .
    command: bundle exec puma -C config/puma.rb -e production
    volumes:
      - .:/GamersPlace
      - public-data:/GamersPlace/public
      - tmp-data:/GamersPlace/tmp
      - log-data:/GamersPlace/log
    networks:
      - GamersPlace-network
  web:
    build:
      context: containers/nginx
    volumes:
      - public-data:/GamersPlace/public
      - tmp-data:/GamersPlace/tmp
    ports:
      - 80:80
    depends_on:
      - app
    networks:
      - GamersPlace-network
volumes:
  mysql-data:
  public-data:
  tmp-data:
  log-data:

networks:
  GamersPlace-network:
    external: true
