# ============= 本番環境 ==================
version: '3'
services:
  app:
    build:
      context: .
    # =========ローカルと本番切り替え===========
    # command: bundle exec puma -C config/puma.rb
    command: bundle exec puma -C config/puma.rb -e production
    # ======================================
    volumes:
      - .:/GamersPlace
      - public-data:/GamersPlace/public
      - tmp-data:/GamersPlace/tmp
      - log-data:/GamersPlace/log
    networks:
      - GamersPlace-network
  web:
    build:
      context: containers/nginx
    volumes:
      - public-data:/GamersPlace/public
      - tmp-data:/GamersPlace/tmp
    ports:
      - 80:80
    depends_on:
      - app
    networks:
      - GamersPlace-network
volumes:
  mysql-data:
  public-data:
  tmp-data:
  log-data:

networks:
  GamersPlace-network:
    external: true
# ======================================


# ============ 開発環境 ===================
# version: '3'
# services:
#   db:
#     image: mysql:5.7
#     environment:
#       - EDITOR=vim
#     volumes:
#       - db-volume:/var/lib/mysql
#     ports:
#       - "4306:3306"

#   app:
#     build: .
#     command: bundle exec puma -C config/puma.rb
#     volumes:
#       - .:/GamersPlace
#       - public-data:/GamersPlace/public
#       - tmp-data:/GamersPlace/tmp
#       - log-data:/GamersPlace/log

#   web:
#     build:
#       context: containers/nginx
#     volumes:
#       - public-data:/GamersPlace/public
#       - tmp-data:/GamersPlace/tmp
#     ports:
#       - 80:80

#   ## テスト環境
#   # chrome:
#   #   image: selenium/standalone-chrome:latest
#   #   ports:
#   #     - 4444:4444

# volumes:
#   db-volume:
#   public-data:
#   tmp-data:
#   log-data:
# ============================================

# ============ 開発環境-old ===================
# version: '3'
# services:
#   web:
#     build: .
#     command: bundle exec rails s -p 3000 -b '0.0.0.0'
#     volumes:
#       - .:/GamersPlace
#     ports:
#       - 3000:3000
#     depends_on:
#       - db
#       - chrome
#     tty: true
#     stdin_open: true
#   db:
#     image: mysql:5.7
#     volumes:
#       - db-volume:/var/lib/mysql
#     environment:
#       - EDITOR=vim
#   chrome:
#     image: selenium/standalone-chrome:latest
#     ports:
#       - 4444:4444
# volumes:
#   db-volume:
# ======================================
