# ============= 本番環境 ==================
version: '3'
services:
  app:
    build: .
    # =========ローカルと本番切り替え===========
    # command: bundle exec puma -C config/puma.rb
    command: bundle exec puma -C config/puma.rb -e production
    # ======================================
    volumes:
      - .:/GamersPlace
      - public-data:/GamersPlace/public
      - tmp-data:/GamersPlace/tmp
      - log-data:/GamersPlace/log
  web:
    build:
      context: containers/nginx
    volumes:
      - public-data:/GamersPlace/public
      - tmp-data:/GamersPlace/tmp
    ports:
      - 80:80
volumes:
  mysql-data:
  public-data:
  tmp-data:
  log-data:
# ======================================
